[features]
skip-lint = false

[programs.mainnet]
triad_protocol = "TRDwq3BN4mP3m9KsuNUWSN6QDff93VKGSwE95Jbr9Ss"

[programs.devnet]
triad_protocol = "3ZmkveqMGGwf4coSRmJuYHCxaQjX1YXjbvM87v71J2P9"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=0beef971-e049-42f3-9688-4af84d7cdea4"
wallet = "/Users/dannpl/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
