[features]
seeds = false
skip-lint = false

[programs.localnet]
triad_protocol = "8naBpcEohvxphPTAcuNHVCZEBDNn5aX41HfqxdcjNQ2W"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dannpl/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
