[features]
skip-lint = false

[programs.devnet]
triad_protocol = "4YWv2Ex8WjFGyXmYELD6Xqs1ZsuQujVUzZxbvdvM2tCj"

[programs.mainnet]
triad_protocol = "TRDwq3BN4mP3m9KsuNUWSN6QDff93VKGSwE95Jbr9Ss"


[provider]
cluster = "devnet"
wallet = "~/.config/solana/triad.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
